config/routes.rb
Classy::Application.routes.draw do
  get "bookmark/create"

  get "bookmark/destroy"

  get "reference/create"

  get "reference/destroy"

  get "password_resets/new"

  get "user_profile/new"

  get "user_profile/update"

  get "user_profile/create"

  get "group_applications/create"

  get "group_applications/destroy"

  get "group_members/create"

  get "group_members/destroy"

  get "group_members/update"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :blurts, only: [:create, :destroy]
  resources :posts, except: [:new] do #new post is handled through the :groups resource
    resources :comments
    member do
      put 'remove_tag', :as => :remove_tag
      post 'add_tag', :as => :add_tag
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :features, only: [:create, :destroy]
  resources :references, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  resources :groups do
    resources :posts, only: [:new]
    member do
      put 'remove_tag', :as => :remove_tag
      post 'add_tag', :as => :add_tag
    end
    collection do
      get 'all', as: 'all'
      get ':id/stats(/:type)' => 'groups#stats', as: 'stats'
      put 'toggle_status/:id' => 'groups#toggle_status', as: 'toggle_status'
    end
  end

  resources :group_applications, only: [:create, :destroy]
  resources :group_members, only: [:create, :destroy, :update]

  resources :admin, only: [:index, :update]

  resources :tags, only: [:show]

  resources :user_profiles, only: [:new, :create, :update, :edit]

  resources :password_resets

  match '/feeds/friends' => 'feeds#friend_feed', as: 'friend_feed'
  match '/feeds/recents' => 'feeds#recent_feed', as: 'recent_feed'

  root :to => "dashboard#home"
  
  match '/help',    to: 'dashboard#help'
  match '/about',   to: 'dashboard#about'
  match '/contact', to: 'dashboard#contact'

  match '/search', to: 'search#index', as: 'search', via: 'POST'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name, :status, :user_id
  
  acts_as_taggable

  has_many :group_members
  has_many :users, :through => :group_members

  has_many :group_applications
  has_many :applications, :through => :group_applications, :source => :user
  
  has_many :posts, :order => 'created_at DESC' 

  has_many :likes, :through => :posts
  has_many :bookmarks, :through => :posts
  has_many :comments, :through => :posts
  has_many :reads, :order=> 'created_at DESC', :through => :posts

  scope :meta, includes([:likes, :bookmarks, :comments])

  validates :name, presence: true, length: { within: 3..50 }, 
  	uniqueness: { case_sensitive: false }

	def is_closed?
		self.status == "closed"
	end

  def is_open?
    self.status == "open"
  end

  def group_admin?(user)
    GroupMember.find_by_group_id_and_user_id(self.id, user.id).role == 'admin'
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  before_filter :signed_in_user
  before_filter :correct_user, only: [:destroy, :edit, :update]
  before_filter :admin_access, only: [:new, :create]
  before_filter :teacher_access, only: [:add_tag, :remove_tag, :stats, :user_stats]

  def index
    @groups = current_user.groups

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @posts }
    end    
  end

  #lists open groups of current_user
  def all
    @groups = Group.where(status: "open")
  end

  def show
    @group = Group.find(params[:id])
    @applications = GroupApplication.where(group_id: @group.id)
    @group_members = @group.users.order('users.email')
    @all_tags = Group.tag_counts.order(:name)
    @group_tags = @group.tag_counts.order(:name)
    @typeahead_tags = @all_tags.map(&:name)
  end

  def new
    @group = Group.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @group }
    end    
  end

  def create
    @group = current_user.groups.build(params[:group])
    @group.status = "open"
    @group.user_id = current_user.id
    if @group.save
      GroupMember.create(group_id: @group.id, user_id: @group.user_id, role: "admin")
      flash[:success] = "Group created!"
      redirect_to groups_path
    else
      flash[:error] = @group.errors
      redirect_to new_group_path
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        #you can only edit the current_group
        @current_group = @group.name
        flash[:success] = "Group updated successfully!"
        format.html  { redirect_to(@group) }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @group.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/toggle_status/:id
  def toggle_status
    @group = Group.find(params[:id])
    if @group.status == "open"
      @group.status = "closed"
    else
      @group.status = "open"
    end

    if @group.save
      flash[:success] = "Group status updated"
    else
      flash[:error] = "Group status change failed"
    end  
    redirect_to @group
  end

  #GET /groups/:id/stats
  def stats
    @chart_type = params[:type] || 'activity'
    case @chart_type
      when "activity"
        @data = Read.created
      when "meta"
        @data = meta_data = @group.likes.select("likes.user_id as user_id, date(likes.created_at) as created_at") + 
                        @group.bookmarks.select("bookmarks.user_id as user_id, date(bookmarks.created_at) as created_at") +
                        @group.comments.select("comments.user_id as user_id, date(comments.created_at) as created_at")
      when "pie"
        @data = Read.created
    end
      
    
    @users = @group.users
    @default_date_from = @group.posts.created.first.created_at
    @default_date_to = [@group.reads.first.created_at, @group.comments.last.created_at, @group.likes.last.created_at, @group.bookmarks.last.created_at].max
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.status = "closed"

    respond_to do |format|
      format.html { redirect_to groups_path }
      format.json { head :no_content }
    end
  end

  def add_tag
    @tag_name = params[:tag]
    new_tags = @group.tags_from(current_user).append(@tag_name).join(',')
    current_user.tag(@group, with: new_tags, on: :tags)
    @tag_response = "tag added"
  end

  def remove_tag
    tag = ActsAsTaggableOn::Tag.find_by_name(params[:tag]) #need to fix to search for "group" and "post" class
    t = ActsAsTaggableOn::Tagging.find_by_tag_id_and_taggable_id_and_taggable_type(tag.id, @group.id, "Group").delete
    flash[:success] = "Tag deleted"
    redirect_to @group
  end

  private

    def correct_user
      @group = Group.find(params[:id])#.group_admin?(current_user)
      redirect_to root_path if @group.nil?
    end

    def admin_access
      redirect_to groups_path, flash: {error: "Access restricted!"} if !Admin.exists?(user_id: current_user.id)
    end

    def teacher_access
      if params.has_key?("group_id")
        @group = Group.find_by_id(params[:group_id])
      else
        @group = Group.find_by_id(params[:id])
      end
      redirect_to groups_path, flash: {error: "Access restricted!"} if !GroupMember.teacher?(current_user.id, @group.id) or !Admin.exists?(user_id: current_user.id)
    end

    def record_not_found
      redirect_to all_groups_path, flash: {error: "Group not found!"}
    end

end

app/helpers/groups_helper.rb
module GroupsHelper

	def user_groups
		if signed_in?
			@header_groups = current_user.groups
			@current_group = current_user.groups.first #change to user preference
		else
			@header_groups = []
			@current_group = nil
		end
	end

	def can_post_to?(group)
		Group.exists?(group) and member?(current_user, group)
	end

	def user_applications(user)
		User.find(user).applications
	end

	def group_user(group)
		Group.find(group).users
	end

	def group_applications(group)
		Group.find(group).applications 
	end

	def member?(user, group)
		GroupMember.find_by_user_id_and_group_id(user,group)
	end

	def toggle_status(group)
		if group.status == "open"
			"Close"
		else
			"Open"
		end
	end
end

app/views/groups/_applicants.html.erb
<% if @applications.count > 0 %>
	<h3>New applications (<%= @applications.count %>)</h3>
	<table class="table table-striped">
		<tr><th>Applicant</th><th>Accept</th><th>Decline</th></tr>
		<% for a in @applications %>
			<tr>
				<td>
					<% user = User.find(a.user_id) %>
					<%= gravatar_for(user, size=32) + ' - ' + link_to(user.email, user) %>
				</td>
				<td>
					<%= button_to "Accept application", group_members_path(group_id: @group.id, user_id: user.id), 
						method: :post, class: "btn btn-mini btn-primary"%>
				</td>
				<td>		
					<%= link_to "Delete Application", 
						group_application_path(@group, user_id: user.id), 
						confirm: 'Are you sure?', method: :delete,
						class: "btn btn-mini btn-danger" %>
				</td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/groups/_edit_group_menu.html.erb
<% if is_group_admin?(group) %>
	<div class="btn-group">
			<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
				Modify group
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li><%= link_to toggle_status(group) + " group", 
          toggle_status_groups_path(group), method: :put %></li>
				<li><%= link_to "Edit group", edit_group_path(group), 
					method: :get %></li>
				<li><%= link_to "Destroy group", group, confirm: 'Are you sure?', 
					 method: :delete %></li>
			</ul>
	</div>
<% end %>

app/views/groups/_edit_role_menu.html.erb
<div class="btn-group">
		<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
			Change role
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to "Make admin", group_member_path(id: user, role: 'admin', group_id: @group.id), 
        method: :put %></li>
      <li><%= link_to "Make teacher", group_member_path(id: user, role: 'teacher', group_id: @group.id), 
        method: :put %></li>
      <li><%= link_to "Make student", group_member_path(id: user, role: 'student', group_id: @group.id), 
        method: :put %></li>      
		</ul>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>

  <%= f.text_area :description, :cols => "30", :rows => "10" %>

  <%= f.submit "Create group", class: "btn btn-large btn-primary" %>

<% end %>

app/views/groups/_group.html.erb
<div class="group">
	<span class="title"><strong><%= @group.name %></strong></span>
	<span class="content"><%= safe_html_output @group.description %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(@group.created_at) %> ago.
	</span>
	<span class="post_edit_actions">
		<% if current_user?(@group.user) %>
			<%= link_to raw("<i class='icon-trash'></i>"), group, method:  :delete,
			                                 confirm: "You sure?",
			                                 title:   @group.name %>
			<%= link_to raw("<i class='icon-edit'></i>"), edit_group_path %>                               
		<% end %>
	</span>
</div>

app/views/groups/_group_members.html.erb
<% if @group_members.count > 0 %>
	<h3>Group Members (<%= @group_members.count %>)</h3>
	<table class="table table-striped">
		<tr><th>User</th><th>Joined</th><th>Role</th><th>Edit</th><th>Actions</th></tr>
		<% for user in @group_members %>
			<tr>
				<td>
					<%= gravatar_for(user, size=32) + ' - ' + link_to(user.name, user) %>
					(<%= user.email %>)
				</td>
				<td><%= time_ago_in_words(GroupMember.find_by_user_id_and_group_id(user, @group).created_at) %> ago</td>
				<td>
					<%= GroupMember.find_by_user_id_and_group_id(user, @group).role %>
				</td>
				<td>
					<%= render partial: 'edit_role_menu', locals: {user: user} %>
				</td>
				<td>
					<%= button_to "Kick", group_member_path(@group), method: :delete,
						class: "btn btn-mini btn-danger" %>
				</td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/groups/_new_group_button.html.erb
<%= link_to_if(is_admin?(current_user), "New group", 
new_group_path, class: "btn btn-medium btn-primary"){} %>

app/views/groups/add_tag.js.erb
location.reload();

app/views/groups/all.html.erb
<%= render 'new_group_button' %>
<table>
	<thead>
		<th>Group</th>
		<th>Creator</th>
		<th>Created</th>
		<th>#Members</th>
		<th>#Posts</th>
		<th>Actions</th>
	</thead>
	<% for group in @groups %>
		<tr>
			<td><%= link_to group.name, group_path(group) %></td>
			<td><%= link_to User.find(group.user_id).name, User.find(group.user_id) %></td>
			<td><%= time_ago_in_words(group.created_at) %></td>
			<td><%= group.users.count %></td>
			<td><%= group.posts.count %></td>
			<td>
				<% if is_member?(group, current_user) %>
					<%= link_to "Leave", group_member_path(group), 
						confirm: 'Are you sure?', method: :delete, class: "btn btn-mini btn-danger" %>
				<% elsif has_application?(group, current_user) %>
					<%= link_to "Delete Application", 
						group_application_path(group, user_id: current_user.id), 
						confirm: 'Are you sure?', method: :delete,
						class: "btn btn-mini btn-danger" %>
				<% else %>
					<%= link_to "Apply to Group", 
						group_applications_path(group: group), method: :post,
						class: "btn btn-mini btn-primary" %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/groups/edit.html.erb
<h1>Edit group</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<%= render 'new_group_button' %>
<%= render 'groups' %>

app/views/groups/new.html.erb
<h1>New group</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<%= link_to_unless(@group.is_closed?, raw("<i class='icon-edit'></i>"), edit_group_path,
	class: "pull-left"){} %>
<%= link_to_unless(@group.is_closed?, raw("<i class='icon-remove'></i>"), edit_group_path, 
	class: "pull-left"){} %>
<%= link_to_unless(@group.is_closed?, "Post to group", new_group_post_path(@group), 
	class: "btn btn-large btn-primary pull-right"){} %>

<h1><%= @group.name %></h1>
<h3>Created by: <%= User.find(@group.user_id).email %></h3>
<p><%= @group.description %></p>

<% if is_group_admin?(@group) %>
	<div class="group" data-id="<%= @group.id %>">
 		<%= text_field_tag :add_post_tag, params[:tags], placeholder: "Add group tag",
			:data => { :provide => 'typeahead', :source => @typeahead_tags},
			class: "span2 tag_form", id: "create_group_tag" %>
	</div>
	<div class="row">
		<div class="span12">
			STATS : 
			<%= link_to 'Reads', stats_groups_path(type: 'activity') %> | 
			<%= link_to 'Meta', stats_groups_path(type: 'meta') %> |
			<%= link_to 'Total reads', stats_groups_path(type: 'pie') %>
		</div>
	</div>
	<%= render partial: 'shared/tags', 
		locals: {title: "Group tags", tags: @group_tags, delete_link: true, group_link_delete: true, print_group_tags: true} %>
	<%= render 'applicants' %>
	<%= render 'group_members' %>
<% end %>

app/views/groups/stats.html.erb
<%= link_to_unless(@group.is_closed?, raw("<i class='icon-edit'></i>"), edit_group_path,
	class: "pull-left"){} %>
<%= link_to_unless(@group.is_closed?, raw("<i class='icon-remove'></i>"), edit_group_path, 
	class: "pull-left"){} %>
<%= link_to_unless(@group.is_closed?, "Post to group", new_group_post_path(@group), 
	class: "btn btn-large btn-primary pull-right"){} %>

<h1><%= @group.name %></h1>
<h3>Created by: <%= User.find(@group.user_id).email %></h3>
<p><%= @group.description %></p>

<script type="text/javascript" charset="utf-8">

function column_chart(data, stacking, render, title, xtitle, ytitle)
{
	new Highcharts.Chart({
	    chart: { 
	    	renderTo: render,
	    	zoomType: 'x',
	    	type: 'column',
	    	animation: false
	    },
	    title: { text: title },
	    xAxis: { 
	    	type: 'datetime',
	    	text: xtitle
	    },
	    yAxis: {
	    	min: 0,
	      	title: { text: ytitle},
	      	stackLabels: {
	                enabled: true,
	                style: {
	                    fontWeight: 'bold',
	                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
	                }
	            }
	    },
	    plotOptions: {
	            column: {
	                stacking: stacking,
	                dataLabels: {
	                    enabled: false,
	                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
	                }
	            }
	    },
	    series: data
	});
}

function pie_chart(data, render, title)
{
	new Highcharts.Chart({
	    chart: {
	        renderTo: render,
	        plotBackgroundColor: null,
	        plotBorderWidth: null,
	        plotShadow: false
	    },
	    title: {
	        text: title
	    },
	    tooltip: {
	        pointFormat: '{series.name}: <b>{Math.round(point.percentage)}%</b>',
	        percentageDecimals: 1
	    },
	    plotOptions: {
	        pie: {
	            allowPointSelect: true,
	            cursor: 'pointer',
	            dataLabels: {
	                enabled: true,
	                color: '#000000',
	                connectorColor: '#000000',
	                formatter: function() {
	                    return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
	                }
	            }
	        }
	    },
	    series: [{
	    	type: 'pie',
	    	name: 'User share',
	    	data: data //format [{name: slice_name, y: %_number, sliced: t/f, selected: t/f}, {}, ...]
	    				//or format [['name', %number],[...], {...}, ...]
	    }]
	});
}

$(function () {
	$( "#percent_chart" ).hide();
	<% 	
		case @chart_type
		when "meta"
			series_data = series_chart_from_a(@data, @default_date_from, @default_date_to)
		else
			series_data = series_chart(@data, @default_date_from, @default_date_to)
		end
	%>	

	<% if @chart_type == "pie" %>
		<% max_activity = series_data.map{|k,v| v.sum}.max %>
		pie_data = [<% @users.each do |user| %>
			["<%= user.name %>", <%= series_data.has_key?(user.id)? (series_data[user.id].sum*1.0/max_activity).round(2) : 0 %>],
		<% end %>]
	<% else %>
		activity_data = [<% @users.each do |user| %>
		    {
		      	name: "<%= user.name %>",
		      	pointInterval: <%= 1.day * 1000 %>,
		      	pointStart: <%= @default_date_from.to_f * 1000 %>,
		      	data: <%= series_data.has_key?(user.id)? series_data[user.id]:[0] %>
		    },
		<% end %>]
	<% end %>

	<% if @chart_type == 'activity' %>
	  	chart = column_chart(activity_data, 'normal', 'chart', 'Reads per day', 'Date', 'Reads');
	  	percent_chart = column_chart(activity_data, 'percent', 'percent_chart', 'Reads per day', 'Date', 'Reads');
	<% elsif @chart_type == 'meta' %>
		chart = column_chart(activity_data, 'normal', 'chart', 'Meta per day', 'Date', 'Meta actions');
  		percent_chart = column_chart(activity_data, 'percent', 'percent_chart', 'Meta per day', 'Date', 'Meta actions');
  	<% elsif @chart_type == 'pie' %>
		chart = pie_chart(pie_data, 'chart', 'User total read activity');
		//hide the buttons
		$("#btn_percent_toggle").hide();
		$("#btn_show_all").hide();
	<% end %>
});

function toggleAll(c) {
    for (var i = 0; i < c.series.length; i++) {
       var serie = c.series[i];
        serie.setVisible(!serie.visible, false);
    }
    c.redraw();
}

function meta_toggle()
{
	if ($("#percent_chart").is(":visible"))
	{
		$("#percent_chart").hide();
		$("#chart").show();
		$("#btn_percent_toggle").html("Meta");
	}
	else
	{
		$("#chart").hide();
		$("#percent_chart").show();
		$("#btn_percent_toggle").html("Normal");
	}
}

</script>

<% if is_group_admin?(@group) %>
	<div class="row">
		<div class="span12">
			STATS : 
			<%= link_to 'Reads', stats_groups_path(type: 'activity') %> | 
			<%= link_to 'Meta', stats_groups_path(type: 'meta') %> |
			<%= link_to 'Total reads', stats_groups_path(type: 'pie') %>
		</div>
	</div>
    <div class="row">
		<div id="chart" style="width: 800px; height: 500px;"></div>
		<div id="percent_chart" style="width: 800px; height: 500px;"></div>
		<button type="button" onclick="toggleAll(chart)" class="btn-small" id="btn_show_all">Show/Hide</button>
		<button type="button" onclick="percent_toggle()" class="btn-small" id="btn_percent_toggle">Percent</button>
	</div>
<% end %>