config/routes.rb
Classy::Application.routes.draw do
  get "bookmark/create"

  get "bookmark/destroy"

  get "reference/create"

  get "reference/destroy"

  get "password_resets/new"

  get "user_profile/new"

  get "user_profile/update"

  get "user_profile/create"

  get "group_applications/create"

  get "group_applications/destroy"

  get "group_members/create"

  get "group_members/destroy"

  get "group_members/update"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :blurts, only: [:create, :destroy]
  resources :posts, except: [:new] do #new post is handled through the :groups resource
    resources :comments
    member do
      put 'remove_tag', :as => :remove_tag
      post 'add_tag', :as => :add_tag
    end
  end
  resources :friendships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :features, only: [:create, :destroy]
  resources :references, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  resources :groups do
    resources :posts, only: [:new]
    member do
      put 'remove_tag', :as => :remove_tag
      post 'add_tag', :as => :add_tag
    end
    collection do
      get 'all', as: 'all'
      get ':id/stats(/:type)' => 'groups#stats', as: 'stats'
      put 'toggle_status/:id' => 'groups#toggle_status', as: 'toggle_status'
    end
  end

  resources :group_applications, only: [:create, :destroy]
  resources :group_members, only: [:create, :destroy, :update]

  resources :admin, only: [:index, :update]

  resources :tags, only: [:show]

  resources :user_profiles, only: [:new, :create, :update, :edit]

  resources :password_resets

  match '/feeds/friends' => 'feeds#friend_feed', as: 'friend_feed'
  match '/feeds/recents' => 'feeds#recent_feed', as: 'recent_feed'

  root :to => "dashboard#home"
  
  match '/help',    to: 'dashboard#help'
  match '/about',   to: 'dashboard#about'
  match '/contact', to: 'dashboard#contact'

  match '/search', to: 'search#index', as: 'search', via: 'POST'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/views/shared/_blurt_form.html.erb
<% if current_user?(@user) %>
	<%= form_for(@blurts) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <div class="field">
	    <%= f.text_area :content, placeholder: "Compose new blurt..." %>
	  </div>
	  <%= f.submit "Blurt", class: "btn btn-medium btn-primary" %>
	<% end %>
<% end %>

app/views/shared/_comment_form.html.erb
<h4>Add a comment</h4>
<div>
	<%= form_for([@post, @post.comments.build]) do |f| %>
	   	<div class="field">
	    	<%= f.text_area :content, placeholder: "Compose new comment..." %>
	  	</div>
	  	<div class="actions">
	    	<%= f.submit "Comment", class: "btn btn-medium btn-primary" %>
	    </div>
	<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if feed_items.any? %>
  <%= will_paginate feed_items %>
    <ol class="blurts">
    	<%= render partial: 'shared/feed_item', collection: feed_items %>
  	</ol>
  <%= will_paginate feed_items %>
<% else %>
	No content for this selection
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>" <% if (feed_item.class == Post) %> 
                                  class="feed_item_post" 
                                <% else %> 
                                  class="feed_item_blurt"
                                <% end %>>
  <div>
    <%= link_to gravatar_for(feed_item.user, size = 64), feed_item.user,
        alt: feed_item.user.name, title: feed_item.user.name %>
    <% if feed_item.respond_to?(:title) %>
      <span class="content">
        <strong>
          <%= link_to feed_item.title, feed_item,
              alt: preview(feed_item.content, 500),
              title: preview(feed_item.content, 500) %>
       </strong> 
       <br/>
       by @<%= link_to feed_item.user.name, feed_item.user %>
       <%= time_ago_in_words(feed_item.created_at) %> ago
       <% if feed_item.class == Post %>
          to <strong><%= feed_item.group.name %></strong>
       <% end %>
      </span>
    <% else %>
      <span>
        Blurt from @<%= link_to feed_item.user.name, feed_item.user %>
        <%= time_ago_in_words(feed_item.created_at) %> ago
      </span>
    <% end %>

    <span class="content">
      <%= safe_html_output summarize(feed_item.content, 300)%>
    </span>
    <span class="timestamp">
      Activity <%= time_ago_in_words(feed_item.updated_at) %> ago.
    </span>

    <% if current_user.try(:id) && current_user.id == feed_item.user.id %>
      <%= link_to raw("<i class='icon-trash'></i>"), feed_item, method:  :delete,
                                       confirm: "You sure?",
                                       title: "Delete",
                                       alt: "Delete" %>
      <% if feed_item.class == Post %>
        <%= link_to raw("<i class='icon-edit'></i>"), edit_post_path(feed_item),
            alt: "Edit", title: "Edit" %> 
      <% end %>
    <% end %>
    <span class="content">
      <% if feed_item.class == Post %>
        <% if feed_item.comments_count > 0 %> 
          <%= feed_item.comments_count %> <i class='icon-comment'></i> 
        <% end %>
        <% if feed_item.likes_count > 0 %> 
          <%= feed_item.likes_count %> <i class='icon-plus-sign'></i> 
        <% end %>
        <% if feed_item.features_count > 0 %> 
          <%= feed_item.features_count %> <i class='icon-goldstar'></i>
        <% end %>
      <% end %> 
    </span>
  </div>
</li>

app/views/shared/_followers.html.erb
<h4><%= link_to "Followers", followers_user_path(@user) %> 
	<span id="nr_followers">(<%= @user.inverse_friendships.count %>)</span>
</h4>
<% if @user.inverse_friendships.empty? %>
	&nbsp;
<% else %>
	<% for friendship in @user.inverse_friendships %>
		<%= link_to raw(gravatar_for friendship.user, size=20), user_path(friendship.user), 
		alt: friendship.user.email, title: friendship.user.email %>
	<% end %>
<% end %>

app/views/shared/_following.html.erb
<h4><%= link_to "Following", following_user_path(@user) %> 
	<span id="nr_following">(<%= @user.friendships.count %>)</span>
</h4>
<% if @user.friendships.empty? %>
	&nbsp;
<% else %>
	<% for friendship in @user.friendships %>
		<%= link_to gravatar_for(friendship.friend, size=20), user_path(friendship.friend), 
		alt: friendship.friend.email, title: friendship.friend.email %>
	<% end %>
<% end %>

app/views/shared/_friendship_stats.html.erb
<% @user ||= current_user %>
<div class="friendship_stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="friends" class="stat">
      <%= @user.friends.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="inverse_friends" class="stat">
      <%= @user.inverse_friends.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_group_tags.html.erb
<h3>Group tags</h3>
<div class="accordion" id="accordion_main">
	<% for group in @user_groups %>
		<div class="accordion-group">

			<div class="accordion-heading">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#tag_accordion" href="#collapse<%=group.id%>">
					<i class="icon-chevron-right"></i> <%=group.name%>
				</a>
			</div>

			<div id="collapse<%=group.id%>" class="accordion-body collapse in">

				<div class="accordion-inner">
					Top tags in <%=group.name%>
				</div>
				<div class="accordion-inner">
					<div class="accordion" id="accordion<%=group.id%>">
						<%  
							group_tags = group.tag_counts.order(:name)
						%>
						<% for tag in group_tags %>
							<%= render partial: 'shared/tag_list', locals: {group_tag: tag} %>
						<% end %>
					</div>
				</div>

			</div>

		</div>
	<% end %>
</div>

app/views/shared/_tag_list.html.erb
<div class="accordion-group">
	<div class="accordion-heading">
		<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion<%=group_tag.id%>" href="#collapse<%=group_tag.id%>">
			<i class="icon-chevron-right"></i> <%=group_tag.name%>
		</a>
	</div>
	<div id="collapse<%=group_tag.id%>" class="accordion-body collapse">
		<%
			other_tags = Post.tagged_with(group_tag.name).tag_counts.where('name != ?',group_tag.name).order('count DESC').limit(7)
		%>
		<% for tag in other_tags %>
			<div class="accordion-inner">
				<%= link_to tag.name, tag_path(tag.name) %> (<%= tag.count %>)
			</div>
		<% end %>
	</div>
</div>

app/views/shared/_tags.html.erb
<% 
if local_assigns.has_key? :print_group_tags
	#filter the tags
	tags.map{ |tag| if !@group_tags.include?(tag) then tag end}
end 

%>
<h3><%= title %></h3>
<% if tags.empty? %>
	No tags
<% else %>
	<% tag_cloud tags, %w(css1 css2 css3 css4) do |a_tag, css_class| %>
		<%
			#print options:
				#print group_tags with color
				#don't print group tags
				#always print non group tags
		%>
		<% if @group_tags.include?(a_tag) and local_assigns.has_key? :print_group_tags %>
			<% #print group_tags with color %>
			<%= link_to a_tag.name, tag_path(a_tag.name), :class => css_class+"c" %>
		<% elsif @group_tags.include?(a_tag) %>
			<% #don't print group tags %>
		<% else %>
			<% #always print non group tags %>
			<%= link_to a_tag.name, tag_path(a_tag.name), :class => css_class %>
		<%end%>
		<% if local_assigns.has_key? :delete_link %>
			<% if local_assigns.has_key? :group_link_delete %>
				<%= link_to raw("<i class='icon-trash'></i>"), remove_tag_group_path(@group, 
					tag: a_tag.name, group_id: @group.id), :method => :put %>
			<% elsif @user_tags.include?(a_tag.name) %>
				<%= link_to raw("<i class='icon-trash'></i>"), remove_tag_post_path(@post, 
					tag: a_tag.name), :method => :put %>
			<% end %>
		<% end %>
	<% end %>
<% end %>
<% if local_assigns.has_key? :print_group_tags %>
	<div class="tag_caption">* Special group tags</div>
<% end %>

app/views/shared/_user_info.html.erb
<section>
  	<%= link_to(@user.name, @user) %> 
  	<%= link_to(raw("<i class='icon-edit'></i>"), edit_user_profile_path(@user)) if @user.id == current_user.id %>
  	<% if @user.id == current_user.id and @user.profile.nil? %>
  		<section>
  			<%= link_to("UPDATE PROFILE", new_user_profile_path, class:"btn btn-danger") %>
  		</section>
  	<% end %>
</section>
<section>
	<a href="<%= user_path(@user) %>">
	  <%= gravatar_for @user %>
	</a>
</section>
<section>
	<%= pluralize(@user.blurts.count, "blurt") %>
	<%= pluralize(@user.posts.count, "post") %>
</section>
<section id="section_following">
	<%= render 'shared/following' %>
</section>
<section id="section_followers">
	<%= render 'shared/followers' %>
</section>

app/views/shared/_user_info_small.html.erb
<section>
	<% if signed_in? %>
		<%= link_to gravatar_for(current_user, size=40), current_user, 
		alt: "This should be a picture of you", title: "This should be a picture of you" %>
		</a>
	<% else %>
		&nbsp;
	<% end %>
</section>